name: Frontend

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.11.1]
        dir: ["client"]
   
    steps:
      - uses: actions/checkout@v3
      - name: Navigate to client directory
        run: cd ${{ matrix.dir }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci && npm run build --if-present
