name: Frontend

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.11.1]
        dir: ["client"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

   
    steps:
      - uses: actions/checkout@v3
      
      - run: npm run build --if-present
        working-directory: ./client
