name: Frontend

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.11.1]
        dir: ["client"]
   
    steps:
      - uses: actions/checkout@v3
     
